<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="11" failed="0" ignored="0" total="11" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="322" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="322" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
      <class name="com.ip.TimeApi.CalendarTest">
        <test-method status="FAIL" signature="setup()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="setup" is-config="true" duration-ms="109" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="testAllocateExactFit()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateExactFit" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateExactFit -->
        <test-method status="SKIP" signature="testAllocateNoWorkPeriods()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateNoWorkPeriods" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateNoWorkPeriods -->
        <test-method status="SKIP" signature="testAllocateOneTaskFailure()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateOneTaskFailure" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateOneTaskFailure -->
        <test-method status="SKIP" signature="testAllocateOneTaskSuccess()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateOneTaskSuccess" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateOneTaskSuccess -->
        <test-method status="SKIP" signature="testAllocateTwoPeriodsFailure()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateTwoPeriodsFailure" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateTwoPeriodsFailure -->
        <test-method status="SKIP" signature="testAllocateTwoPeriodsSuccess()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateTwoPeriodsSuccess" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateTwoPeriodsSuccess -->
        <test-method status="SKIP" signature="testAllocateTwoTasksSuccess()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateTwoTasksSuccess" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateTwoTasksSuccess -->
        <test-method status="SKIP" signature="testAllocateWorkPeriodsInPast()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testAllocateWorkPeriodsInPast" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateWorkPeriodsInPast -->
        <test-method status="SKIP" signature="testNoTasksNoPeriods()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testNoTasksNoPeriods" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNoTasksNoPeriods -->
        <test-method status="SKIP" signature="testNowNearEndOfPeriodFails()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testNowNearEndOfPeriodFails" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNowNearEndOfPeriodFails -->
        <test-method status="SKIP" signature="testNowNearEndOfPeriodSucceeds()[pri:0, instance:com.ip.TimeApi.CalendarTest@3701eaf6]" name="testNowNearEndOfPeriodSucceeds" duration-ms="0" started-at="2020-06-02T00:34:49 PDT" finished-at="2020-06-02T00:34:49 PDT">
          <exception class="java.time.DateTimeException">
            <message>
              <![CDATA[Invalid value for Year (valid values -999999999 - 999999999): 1000000000]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.time.LocalDate.ofEpochDay(Unknown Source)
at java.time.LocalDate.plusDays(Unknown Source)
at java.time.LocalDateTime.plusDays(Unknown Source)
at com.ip.TimeApi.WorkPeriod.validatePeriodTimes(WorkPeriod.java:35)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:31)
at com.ip.TimeApi.WorkPeriod.<init>(WorkPeriod.java:24)
at com.ip.TimeApi.CalendarTest.setup(CalendarTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.time.DateTimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNowNearEndOfPeriodSucceeds -->
      </class> <!-- com.ip.TimeApi.CalendarTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
